services:
  excalidraw:
    build:
      context: .
      args:
        - NODE_ENV=development
        - VITE_APP_WS_SERVER_URL=http://localhost:8010
    container_name: excalidraw
    ports:
      - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    depends_on:
      - collab-server

  collab-server:
    build:
      context: ./collab-server
    container_name: collab-server
    ports:
      - "8010:8000"
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
